/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AviatorRouteImport } from './routes/aviator'
import { Route as BlackjackRouteImport } from './routes/blackjack'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramWebhookHandlerRouteImport } from './routes/api/public/telegram/webhook-handler'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AviatorRoute = AviatorRouteImport.update({
  id: '/aviator',
  path: '/aviator',
  getParentRoute: () => rootRouteImport,
} as any)
const BlackjackRoute = BlackjackRouteImport.update({
  id: '/blackjack',
  path: '/blackjack',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookHandlerRoute =
  ApiPublicTelegramWebhookHandlerRouteImport.update({
    id: '/api/public/telegram/webhook-handler',
    path: '/api/public/telegram/webhook-handler',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aviator': typeof AviatorRoute
  '/blackjack': typeof BlackjackRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/rooms': typeof RoomsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/telegram/webhook-handler': typeof ApiPublicTelegramWebhookHandlerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aviator': typeof AviatorRoute
  '/blackjack': typeof BlackjackRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/rooms': typeof RoomsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/telegram/webhook-handler': typeof ApiPublicTelegramWebhookHandlerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aviator': typeof AviatorRoute
  '/blackjack': typeof BlackjackRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/rooms': typeof RoomsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/telegram/webhook-handler': typeof ApiPublicTelegramWebhookHandlerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aviator'
    | '/blackjack'
    | '/dashboard'
    | '/history'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/rooms'
    | '/api/public/telegram/webhook'
    | '/api/public/telegram/webhook-handler'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/aviator'
    | '/blackjack'
    | '/dashboard'
    | '/history'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/rooms'
    | '/api/public/telegram/webhook'
    | '/api/public/telegram/webhook-handler'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aviator'
    | '/blackjack'
    | '/dashboard'
    | '/history'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/rooms'
    | '/api/public/telegram/webhook'
    | '/api/public/telegram/webhook-handler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AviatorRoute: typeof AviatorRoute
  BlackjackRoute: typeof BlackjackRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RoomsRoute: typeof RoomsRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicTelegramWebhookHandlerRoute: typeof ApiPublicTelegramWebhookHandlerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviator': {
      id: '/aviator'
      path: '/aviator'
      fullPath: '/aviator'
      preLoaderRoute: typeof AviatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blackjack': {
      id: '/blackjack'
      path: '/blackjack'
      fullPath: '/blackjack'
      preLoaderRoute: typeof BlackjackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook-handler': {
      id: '/api/public/telegram/webhook-handler'
      path: '/api/public/telegram/webhook-handler'
      fullPath: '/api/public/telegram/webhook-handler'
      preLoaderRoute: typeof ApiPublicTelegramWebhookHandlerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AviatorRoute: AviatorRoute,
  BlackjackRoute: BlackjackRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LeaderboardRoute: LeaderboardRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RoomsRoute: RoomsRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicTelegramWebhookHandlerRoute: ApiPublicTelegramWebhookHandlerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
